// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"database/sql"
	"meido-anime-server/etc"
	"meido-anime-server/internal/api/v1"
	"meido-anime-server/internal/app"
	"meido-anime-server/internal/repo"
	"meido-anime-server/internal/service"
)

// Injectors from common.go:

func NewDB() *sql.DB {
	config := etc.NewConfig()
	db := app.NewDB(config)
	return db
}

// Injectors from rss.go:

func NewRssRepo() repo.RssInterface {
	db := NewDB()
	rssInterface := repo.NewRssRepo(db)
	return rssInterface
}

func NewRssService() *service.RssService {
	rssInterface := NewRssRepo()
	rssService := service.NewRssService(rssInterface)
	return rssService
}

func NewRssApi() *v1.RssApi {
	rssService := NewRssService()
	rssApi := v1.NewRssApi(rssService)
	return rssApi
}

// Injectors from video.go:

func NewVideoRepo() repo.VideoInterface {
	db := NewDB()
	videoInterface := repo.NewVideoRepo(db)
	return videoInterface
}

func NewVideoService() *service.VideoService {
	videoInterface := NewVideoRepo()
	videoService := service.NewVideoService(videoInterface)
	return videoService
}

func NewVideoApi() *v1.VideoApi {
	videoService := NewVideoService()
	videoApi := v1.NewVideoApi(videoService)
	return videoApi
}
