// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"database/sql"
	"meido-anime-server/etc"
	"meido-anime-server/internal/api/v1"
	"meido-anime-server/internal/app"
	"meido-anime-server/internal/repo"
	"meido-anime-server/internal/service"
)

// Injectors from common.go:

func NewDB() *sql.DB {
	config := etc.NewConfig()
	db := app.NewDB(config)
	return db
}

// Injectors from demo.go:

func NewDemoRepo() repo.IDemoRepo {
	db := NewDB()
	iDemoRepo := repo.NewDemoRepo(db)
	return iDemoRepo
}

func NewDemoService() *service.DemoService {
	iDemoRepo := NewDemoRepo()
	demoService := service.NewDemoService(iDemoRepo)
	return demoService
}

func NewDemoHander() *v1.DemoHandler {
	demoService := NewDemoService()
	demoHandler := v1.NewDemoHandler(demoService)
	return demoHandler
}
