// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/imroc/req/v3"
	"github.com/jmoiron/sqlx"
	"meido-anime-server/config"
	"meido-anime-server/internal/api/v1"
	"meido-anime-server/internal/common"
	"meido-anime-server/internal/middleware"
	"meido-anime-server/internal/repo"
	"meido-anime-server/internal/service"
	"meido-anime-server/internal/tool"
)

// Injectors from bangumi.go:

func NewBangumiRepo() *repo.BangumiRepo {
	client := NewBangumiClient()
	bangumiRepo := repo.NewBangumiRepo(client)
	return bangumiRepo
}

func NewBangumiService() *service.BangumiService {
	bangumiRepo := NewBangumiRepo()
	bangumiService := service.NewBangumiService(bangumiRepo)
	return bangumiService
}

func NewBangumiApi() *v1.BangumiApi {
	bangumiService := NewBangumiService()
	bangumiApi := v1.NewBangumiApi(bangumiService)
	return bangumiApi
}

// Injectors from common.go:

func NewConfig() *config.Config {
	configConfig := config.NewConfig()
	return configConfig
}

func NewMiddleware() *middleware.Middleware {
	configConfig := NewConfig()
	middlewareMiddleware := middleware.NewMiddleware(configConfig)
	return middlewareMiddleware
}

func NewDB() *sqlx.DB {
	configConfig := NewConfig()
	db := common.NewDB(configConfig)
	return db
}

func NewDBClient() common.DBClient {
	db := NewDB()
	dbClient := common.NewDBClient(db)
	return dbClient
}

func NewSqlTool() *tool.Sql {
	sql := tool.NewSql()
	return sql
}

func NewQB() *common.QB {
	configConfig := NewConfig()
	qb := common.NewQB(configConfig)
	return qb
}

func NewBangumiClient() *req.Client {
	client := common.NewBangumiClient()
	return client
}

// Injectors from cron.go:

func NewCronService() *service.CronService {
	videoService := NewVideoService()
	cronService := service.NewCronService(videoService)
	return cronService
}

// Injectors from init.go:

func NewInitService() *service.InitService {
	videoService := NewVideoService()
	cronService := NewCronService()
	initService := service.NewInitService(videoService, cronService)
	return initService
}

// Injectors from rss.go:

func NewRssService() *service.RssService {
	rssService := service.NewRssService()
	return rssService
}

func NewRssApi() *v1.RssApi {
	rssService := NewRssService()
	rssApi := v1.NewRssApi(rssService)
	return rssApi
}

// Injectors from torrent_client.go:

func NewQbittorrentClient() repo.TorrentClientInterface {
	qb := NewQB()
	torrentClientInterface := repo.NewQbittorrent(qb)
	return torrentClientInterface
}

// Injectors from user.go:

func NewUserService() *service.UserService {
	userService := service.NewUserService()
	return userService
}

func NewUserApi() *v1.UserApi {
	userService := NewUserService()
	userApi := v1.NewUserApi(userService)
	return userApi
}

// Injectors from video.go:

func NewVideoRepo() repo.VideoInterface {
	dbClient := NewDBClient()
	sql := NewSqlTool()
	videoInterface := repo.NewVideoRepo(dbClient, sql)
	return videoInterface
}

func NewVideoService() *service.VideoService {
	videoInterface := NewVideoRepo()
	torrentClientInterface := NewQbittorrentClient()
	videoService := service.NewVideoService(videoInterface, torrentClientInterface)
	return videoService
}

func NewVideoApi() *v1.VideoApi {
	videoService := NewVideoService()
	videoApi := v1.NewVideoApi(videoService)
	return videoApi
}
