name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      DOCKER_NAME: meido-anime-server
      REMOTE_PROJECT_DIR: /home/project/meido-anime-server
      REMOTE_DOCKER_DIR: /home/project/meido-anime-server/docker-image
      REMOTE_MEDIA_DIR: /home/media/meido-anime
      REMOTE_QB_DOWNLOADS_DIR: /home/docker/qbittorrent/downloads



    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker build image
        run: |
          docker build -t ${{ env.DOCKER_NAME }} .
      - name: docker save image
        run: docker save -o ${{ env.DOCKER_NAME }}.tar ${{ env.DOCKER_NAME }}

      - name: scp docker image
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_HOST }}
          password: ${{ secrets.DEV_REMOTE_PASSWORD }}
          username: ${{ secrets.DEV_REMOTE_USERNAME }}
          port: ${{ secrets.DEV_REMOTE_PORT }}

          source: "${{ env.DOCKER_NAME }}.tar"
          target: ${{ env.REMOTE_DOCKER_DIR }}
          rm: true


      - name: ssh run docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_HOST }}
          password: ${{ secrets.DEV_REMOTE_PASSWORD }}
          username: ${{ secrets.DEV_REMOTE_USERNAME }}
          port: ${{ secrets.DEV_REMOTE_PORT }}

          script: |
            cd ${{ env.REMOTE_DOCKER_DIR }}
            
            docker stop ${{ env.DOCKER_NAME }}
            docker rm ${{ env.DOCKER_NAME }}
            
            docker load -i ${{ env.DOCKER_NAME }}.tar
            
            docker run -d --name ${{ env.DOCKER_NAME }} -v ${{ env.REMOTE_PROJECT_DIR }}/config:/config -v ${{ env.REMOTE_PROJECT_DIR }}/db/:/db/ -v ${{ env.REMOTE_QB_DOWNLOADS_DIR }}:/downloads -e QB_CATEGORY=meido -e QB_DOWNLOADS_PATH=/downloads -e SOURCE_PATH=/downloads -v ${{ env.REMOTE_MEDIA_DIR }}:/media -e MEDIA_PATH=/media -e QB_WEB_URL=${{ secrets.DEV_QB_WEB_URL }} -e QB_USERNAME=${{ secrets.DEV_QB_USERNAME }} -e QB_PASSWORD=${{ secrets.DEV_QB_PASSWORD }} -p ${{ secrets.DEV_PROJECT_PORT }}:8081 ${{ env.DOCKER_NAME }}
            
            docker image prune -f