name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker build image
        run: |
          docker build -t ${{ secrets.DEV_DOCKER_NAME }} .
      - name: docker save image
        run: docker save -o ${{ secrets.DEV_DOCKER_NAME }}.tar ${{ secrets.DEV_DOCKER_NAME }}

      - name: scp docker image
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_HOST }}
          password: ${{ secrets.DEV_REMOTE_PASSWORD }}
          username: ${{ secrets.DEV_REMOTE_USERNAME }}
          port: ${{ secrets.DEV_REMOTE_PORT }}

          source: "${{ secrets.DEV_DOCKER_NAME }}.tar"
          target: ${{ secrets.DEV_REMOTE_TARGET }}
          rm: true


      - name: ssh run docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_HOST }}
          password: ${{ secrets.DEV_REMOTE_PASSWORD }}
          username: ${{ secrets.DEV_REMOTE_USERNAME }}
          port: ${{ secrets.DEV_REMOTE_PORT }}

          script: |
            cd ${{ secrets.DEV_REMOTE_TARGET }}
            
            docker stop ${{ secrets.DEV_DOCKER_NAME }}
            docker rm ${{ secrets.DEV_DOCKER_NAME }}
            
            docker load -i ${{ secrets.DEV_DOCKER_NAME }}.tar
            
            docker run -d --name ${{ secrets.DEV_DOCKER_NAME }} -v /home/docker/qbittorrent/downloads:/downloads -e SOURCE_PATH=/downloads -v /home/media/meido-anime:/media -e MEDIA_PATH=/media -e QB_WEB_URL=${{ secrets.DEV_QB_WEB_URL }} -e QB_USERNAME=${{ secrets.DEV_QB_USERNAME }} -e QB_PASSWORD=${{ secrets.DEV_QB_PASSWORD }} -e QB_CATEGORY=meido -e QB_DOWNLOADS_PATH=/downloads -e USERNAME=${{ secrets.DEV_QB_USERNAME }} -e PASSWORD=${{ secrets.DEV_QB_PASSWORD }} -p ${{ secrets.DEV_PROJECT_PORT }}:8081 
            ${{ secrets.DEV_DOCKER_NAME }}
            
            docker image prune -f